### PR TITLE
Makes search, filters, and sort more obvious

### LINKED ISSUE #370: Request to Review sorted by Start Date by default
Will prioritize requests that are time-sensitive / going to occur soon

Related to #380

### PR DESCRIPTION
**Pull request by axamei**
Closes #370

### CODE REVIEW

**Comment by axamei** [comment]
@sdellis Feel free to play with the colors

**Comment by sdellis** [comment]
@axamei I feel like we should have a gradient of a specific color for this situation in our [design tokens](https://pulibrary.github.io/lux/docs/#/Design%20Tokens) Color Palette. We have this for Grayscale (see screenshot), but the Tan options don't really reflect that. I don't think the grayscale works in this context, but we should have some colors that do.

Also, it would be nice to have the bg color that we're using as one of the Lux palette options. I noticed that we aren't using Sass in Approvals? If we were we could easily import the Lux color variables, and the UI colors would evolve as our color palette does. What do you think? 

filter-group-colors

**Comment by axamei** [comment]
@sdellis that's a good idea. there's definitely some cleanup needed in the application css file. i will add some colors to the design tokens in lux and refactor the rails styles.

**Comment by axamei** [comment]
@sdellis What do you think about this?
Screen Shot 2019-12-06 at 10 00 47 AM

**Comment by sdellis** [comment]
@axamei that looks good to me!

**Pull request merged**
