### PR TITLE
[WIP] Refactors main menu and request type filter to use children

### PR DESCRIPTION
**Pull request by axamei**
Blocked by https://github.com/pulibrary/lux/pull/295

Tests are failing and LUX version needs to be bumped up for this to work.

I was unable to comment out the absence request types in the request list. Maybe we can just remove it for now since the code is version controlled.

I was also not sure about the IA of the main menu. I put "New travel request" under "My requests". Feel free to refactor.

### CODE REVIEW

**Comment by sdellis** [comment]
I think that the only thing remaining is that the `My Account` top-level menu item  in LibraryHeader does not have a link associated with it, and currently goes nowhere. If we're ok with that, this is ready to merge.

**Comment by sdellis** [comment]
@carolyncole I had to update a capybara test with the new submenus in the LibraryHeader. It passes, but doesn't cover the spirit of the test, which is to see if the Delegations and My Delegate options are present. I couldn't figure out how to set `focus` to the top-level menu item (My Account) in capybara so that the dropdown becomes visible. Do you know how to do this?

**Comment by carolyncole** [comment]
We want the top level items to be buttons not links, and those just open the menu.
Requests & netid instead of my account.
New Travel Requests,  Reports, My Requests, and  links would end up under requests.
Requests to review will remain on the top

**Comment by axamei** [comment]
Closing this in favor of #603

**Pull request closed without merging**
