### PR TITLE
Upgrade rails-webpacker

### PR DESCRIPTION
**Pull request by sandbergja**
I wasn't able to `yarn install` locally until I upgraded this npm package.

### CODE REVIEW

**Review by maxkadel — CHANGES_REQUESTED** [review]
This works for me locally but is not deploying successfully - see https://gist.github.com/pulbot/39d598d1f749f719fbba6f0f4d48c387

**Comment by sandbergja** [comment]
I retried this upgrade today, and it seems to be deploying now.  Could you please re-review @maxkadel ?

**Review by christinach — APPROVED** [review]

**Comment by sandbergja** [comment]
rebased and fixed a small merge conflict

**Review by maxkadel — APPROVED** [review]
🎉

**Pull request merged**
