### PR TITLE
Partial implementation of home page

### PR DESCRIPTION
**Pull request by hackmastera**
Partial implementation of home page. advances #26

### CODE REVIEW

**Comment by hackmastera** [comment]
here's a screenshot; content needs to be centered and margins need to be different between mobile and full-size.
Screen Shot 2019-06-06 at 2 39 13 PM

**Comment by hackmastera** [comment]
I think this is fine to merge, and there are some remaining questions for closing the ticket.
- The content should be centered. Should lux be involved here at all, or should we just write some local styles. I assume local but I'm trying to make sure I use lux as much as it allows.
- The content should have large margins for a full-size screen and small margins for a small screen. Does lux provide breakpoints for those styles? I don't think the grid is quite the same thing, but if there's a technique that would use the grid I'd appreciate some guidance.

**Comment by sdellis** [comment]
@hackmastera yes, go ahead and merge this. I think that any UI needs that are not immediately intuitive when using LUX can be passed to @axamei and me via new tickets. I see that as a reasonable delegation of responsibilities, and I don't want any discussions about how to handle these details to hold up progress on the backend. 

There's the concept of a "template" in LUX. A "template" is an entire page (or significant part of a page) bundled as a component. In fact, we have a ["homepage" template](https://pulibrary.github.io/lux/docs/#/Templates/Index) that came with VueDS that we haven't adapted for our own needs yet. I'm not sure we will go that route, but this is the first time we've had a chance to think through some of these decisions so bear with us. :)

**Comment by hackmastera** [comment]
@sdellis thanks; do you think that #26 could be the ticket to track the remaining questions? Or do you want sub-tickets? Or do you want lux tickets?

**Pull request merged**
